-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "TaskList" ADD VALUE 'CHECKED_SOCIAL_MEDIA';
ALTER TYPE "TaskList" ADD VALUE 'SUBSCRIBED_SOUL_FORUM';
ALTER TYPE "TaskList" ADD VALUE 'SUBSCRIBED_INSTAGRAM';
ALTER TYPE "TaskList" ADD VALUE 'SHARED_ABOUT_SOUL';
ALTER TYPE "TaskList" ADD VALUE 'SHARED_WITH_FRIEND';
ALTER TYPE "TaskList" ADD VALUE 'ADDED_REFLINK_IN_TG_PROFILE';
ALTER TYPE "TaskList" ADD VALUE 'PREMIUM_SUPPORT';
ALTER TYPE "TaskList" ADD VALUE 'VOTED_SOUL_FORUM';
ALTER TYPE "TaskList" ADD VALUE 'SHARED_STORY_IN_TG';
ALTER TYPE "TaskList" ADD VALUE 'VIEWED_HOW_IT_WORKS';
ALTER TYPE "TaskList" ADD VALUE 'CREATED_FIRST_MEETING';
ALTER TYPE "TaskList" ADD VALUE 'HOLDED_MEETINGS';
ALTER TYPE "TaskList" ADD VALUE 'HOLDED_1_MEETINGS';
ALTER TYPE "TaskList" ADD VALUE 'HOLDED_5_MEETINGS';
ALTER TYPE "TaskList" ADD VALUE 'HOLDED_10_MEETINGS';
ALTER TYPE "TaskList" ADD VALUE 'HOLDED_20_MEETINGS';
ALTER TYPE "TaskList" ADD VALUE 'HOLDED_50_MEETINGS';
ALTER TYPE "TaskList" ADD VALUE 'MAX_GUESTS_IN_MEETING';
ALTER TYPE "TaskList" ADD VALUE 'MAX_GUESTS_5_IN_MEETING';
ALTER TYPE "TaskList" ADD VALUE 'MAX_GUESTS_10_IN_MEETING';
ALTER TYPE "TaskList" ADD VALUE 'MAX_GUESTS_20_IN_MEETING';
ALTER TYPE "TaskList" ADD VALUE 'MAX_GUESTS_50_IN_MEETING';
ALTER TYPE "TaskList" ADD VALUE 'INVITED_FRIENDS';
ALTER TYPE "TaskList" ADD VALUE 'INVITED_1_FRIENDS';
ALTER TYPE "TaskList" ADD VALUE 'INVITED_5_FRIENDS';
ALTER TYPE "TaskList" ADD VALUE 'INVITED_10_FRIENDS';
ALTER TYPE "TaskList" ADD VALUE 'INVITED_20_FRIENDS';
ALTER TYPE "TaskList" ADD VALUE 'INVITED_50_FRIENDS';
ALTER TYPE "TaskList" ADD VALUE 'INVITED_100_FRIENDS';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_10_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_50_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_100_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_250_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_500_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_1000_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_2500_SP';
ALTER TYPE "TaskList" ADD VALUE 'COLLECTED_5000_SP';
