export const currency = [
  { code: 'USD' }, // "United States Dollar"
  { code: 'EUR' }, // "Euro"
  { code: 'RUB' }, // "Russian Ruble"
  { code: 'INR' }, // "Indian Rupee"
  { code: 'IDR' }, // "Indonesian Rupiah"
  { code: 'THB' }, // "Thai Baht"
  { code: 'VND' }, // "Vietnamese Dong"
  { code: 'AED' }, // "United Arab Emirates Dirham",
  { code: 'GBP' }, // "British Pound Sterling"
  { code: 'JPY' }, // "Japanese Yen"
  { code: 'CNY' }, // "Chinese Yuan"
  { code: 'AUD' }, // "Australian Dollar"
  { code: 'CAD' }, // "Canadian Dollar"
  { code: 'CHF' }, // "Swiss Franc"
  { code: 'HKD' }, // "Hong Kong Dollar"
  { code: 'SGD' }, // "Singapore Dollar"
  { code: 'AFN' }, // "Afghan Afghani"
  { code: 'ALL' }, // "Albanian Lek"
  { code: 'AMD' }, // "Armenian Dram"
  { code: 'ANG' }, // "Netherlands Antillean Guilder"
  { code: 'AOA' }, // "Angolan Kwanza"
  { code: 'ARS' }, // "Argentine Peso"
  { code: 'AWG' }, // "Aruban Florin"
  { code: 'AZN' }, // "Azerbaijani Manat"
  { code: 'BAM' }, // "Bosnia-Herzegovina Convertible Mark"
  { code: 'BBD' }, // "Barbadian Dollar"
  { code: 'BDT' }, // "Bangladeshi Taka"
  { code: 'BGN' }, // "Bulgarian Lev"
  { code: 'BHD' }, // "Bahraini Dinar"
  { code: 'BIF' }, // "Burundian Franc"
  { code: 'BMD' }, // "Bermudan Dollar"
  { code: 'BND' }, // "Brunei Dollar"
  { code: 'BOB' }, // "Bolivian Boliviano"
  { code: 'BRL' }, // "Brazilian Real"
  { code: 'BSD' }, // "Bahamian Dollar"
  { code: 'BTN' }, // "Bhutanese Ngultrum"
  { code: 'BWP' }, // "Botswanan Pula"
  { code: 'BYN' }, // "Belarusian Ruble"
  { code: 'BZD' }, // "Belize Dollar"
  { code: 'CDF' }, // "Congolese Franc"
  { code: 'CLF' }, // "Chilean Unit of Account (UF)"
  { code: 'CLP' }, // "Chilean Peso"
  { code: 'CNH' }, // "Chinese Yuan (Offshore)"
  { code: 'COP' }, // "Colombian Peso"
  { code: 'CRC' }, // "Costa Rican Colón"
  { code: 'CUC' }, // "Cuban Convertible Peso"
  { code: 'CUP' }, // "Cuban Peso"
  { code: 'CVE' }, // "Cape Verdean Escudo"
  { code: 'CZK' }, // "Czech Republic Koruna"
  { code: 'DJF' }, // "Djiboutian Franc"
  { code: 'DKK' }, // "Danish Krone"
  { code: 'DOP' }, // "Dominican Peso"
  { code: 'DZD' }, // "Algerian Dinar"
  { code: 'EGP' }, // "Egyptian Pound"
  { code: 'ERN' }, // "Eritrean Nakfa"
  { code: 'ETB' }, // "Ethiopian Birr"
  { code: 'FJD' }, // "Fijian Dollar"
  { code: 'FKP' }, // "Falkland Islands Pound"
  { code: 'GEL' }, // "Georgian Lari"
  { code: 'GGP' }, // "Guernsey Pound"
  { code: 'GHS' }, // "Ghanaian Cedi"
  { code: 'GIP' }, // "Gibraltar Pound"
  { code: 'GMD' }, // "Gambian Dalasi"
  { code: 'GNF' }, // "Guinean Franc"
  { code: 'GTQ' }, // "Guatemalan Quetzal"
  { code: 'GYD' }, // "Guyanaese Dollar"
  { code: 'HNL' }, // "Honduran Lempira"
  { code: 'HRK' }, // "Croatian Kuna"
  { code: 'HTG' }, // "Haitian Gourde"
  { code: 'HUF' }, // "Hungarian Forint"
  { code: 'ILS' }, // "Israeli New Sheqel"
  { code: 'IMP' }, // "Manx pound"
  { code: 'IQD' }, // "Iraqi Dinar"
  { code: 'IRR' }, // "Iranian Rial"
  { code: 'ISK' }, // "Icelandic Króna"
  { code: 'JEP' }, // "Jersey Pound"
  { code: 'JMD' }, // "Jamaican Dollar"
  { code: 'JOD' }, // "Jordanian Dinar"
  { code: 'KES' }, // "Kenyan Shilling"
  { code: 'KGS' }, // "Kyrgystani Som"
  { code: 'KHR' }, // "Cambodian Riel"
  { code: 'KMF' }, // "Comorian Franc"
  { code: 'KPW' }, // "North Korean Won"
  { code: 'KRW' }, // "South Korean Won"
  { code: 'KWD' }, // "Kuwaiti Dinar"
  { code: 'KYD' }, // "Cayman Islands Dollar"
  { code: 'KZT' }, // "Kazakhstani Tenge"
  { code: 'LAK' }, // "Laotian Kip"
  { code: 'LBP' }, // "Lebanese Pound"
  { code: 'LKR' }, // "Sri Lankan Rupee"
  { code: 'LRD' }, // "Liberian Dollar"
  { code: 'LSL' }, // "Lesotho Loti"
  { code: 'LYD' }, // "Libyan Dinar"
  { code: 'MAD' }, // "Moroccan Dirham"
  { code: 'MDL' }, // "Moldovan Leu"
  { code: 'MGA' }, // "Malagasy Ariary"
  { code: 'MKD' }, // "Macedonian Denar"
  { code: 'MMK' }, // "Myanma Kyat"
  { code: 'MNT' }, // "Mongolian Tugrik"
  { code: 'MOP' }, // "Macanese Pataca"
  { code: 'MRU' }, // "Mauritanian Ouguiya"
  { code: 'MUR' }, // "Mauritian Rupee"
  { code: 'MVR' }, // "Maldivian Rufiyaa"
  { code: 'MWK' }, // "Malawian Kwacha"
  { code: 'MXN' }, // "Mexican Peso"
  { code: 'MYR' }, // "Malaysian Ringgit"
  { code: 'MZN' }, // "Mozambican Metical"
  { code: 'NAD' }, // "Namibian Dollar"
  { code: 'NGN' }, // "Nigerian Naira"
  { code: 'NIO' }, // "Nicaraguan Córdoba"
  { code: 'NOK' }, // "Norwegian Krone"
  { code: 'NPR' }, // "Nepalese Rupee"
  { code: 'NZD' }, // "New Zealand Dollar"
  { code: 'OMR' }, // "Omani Rial"
  { code: 'PAB' }, // "Panamanian Balboa"
  { code: 'PEN' }, // "Peruvian Nuevo Sol"
  { code: 'PGK' }, // "Papua New Guinean Kina"
  { code: 'PHP' }, // "Philippine Peso"
  { code: 'PKR' }, // "Pakistani Rupee"
  { code: 'PLN' }, // "Polish Zloty"
  { code: 'PYG' }, // "Paraguayan Guarani"
  { code: 'QAR' }, // "Qatari Rial"
  { code: 'RON' }, // "Romanian Leu"
  { code: 'RSD' }, // "Serbian Dinar"
  { code: 'RWF' }, // "Rwandan Franc"
  { code: 'SAR' }, // "Saudi Riyal"
  { code: 'SBD' }, // "Solomon Islands Dollar"
  { code: 'SCR' }, // "Seychellois Rupee"
  { code: 'SDG' }, // "Sudanese Pound"
  { code: 'SEK' }, // "Swedish Krona"
  { code: 'SHP' }, // "Saint Helena Pound"
  { code: 'SLL' }, // "Sierra Leonean Leone"
  { code: 'SOS' }, // "Somali Shilling"
  { code: 'SRD' }, // "Surinamese Dollar"
  { code: 'SSP' }, // "South Sudanese Pound"
  { code: 'STD' }, // "São Tomé and Príncipe Dobra (pre-2018)"
  { code: 'STN' }, // "São Tomé and Príncipe Dobra"
  { code: 'SVC' }, // "Salvadoran Colón"
  { code: 'SYP' }, // "Syrian Pound"
  { code: 'SZL' }, // "Swazi Lilangeni"
  { code: 'TJS' }, // "Tajikistani Somoni"
  { code: 'TMT' }, // "Turkmenistani Manat"
  { code: 'TND' }, // "Tunisian Dinar"
  { code: 'TOP' }, // "Tongan Pa'anga"
  { code: 'TRY' }, // "Turkish Lira"
  { code: 'TTD' }, // "Trinidad and Tobago Dollar"
  { code: 'TWD' }, // "New Taiwan Dollar"
  { code: 'TZS' }, // "Tanzanian Shilling"
  { code: 'UAH' }, // "Ukrainian Hryvnia"
  { code: 'UGX' }, // "Ugandan Shilling"
  { code: 'UYU' }, // "Uruguayan Peso"
  { code: 'UZS' }, // "Uzbekistan Som"
  { code: 'VEF' }, // "Venezuelan Bolívar Fuerte (Old)"
  { code: 'VES' }, // "Venezuelan Bolívar Soberano"
  { code: 'VUV' }, // "Vanuatu Vatu"
  { code: 'WST' }, // "Samoan Tala"
  { code: 'XAF' }, // "CFA Franc BEAC"
  { code: 'XAG' }, // "Silver Ounce"
  { code: 'XAU' }, // "Gold Ounce"
  { code: 'XCD' }, // "East Caribbean Dollar"
  { code: 'XDR' }, // "Special Drawing Rights"
  { code: 'XOF' }, // "CFA Franc BCEAO"
  { code: 'XPD' }, // "Palladium Ounce"
  { code: 'XPF' }, // "CFP Franc"
  { code: 'XPT' }, // "Platinum Ounce"
  { code: 'YER' }, // "Yemeni Rial"
  { code: 'ZAR' }, // "South African Rand"
  { code: 'ZMW' }, // "Zambian Kwacha"
  { code: 'ZWL' }, // "Zimbabwean Dollar"
];
