import { TaskList, TaskType } from '@prisma/client';

export const tasks = [
  {
    key: TaskList.CHECKIN,
    type: TaskType.DAILY,
    title: 'Ежедневный чекин',
    description: 'Заходи каждый день, чтобы получить награды!',
    goal: 7,
    rewardSp: 0, //награды прописаны в константах
  },
  {
    key: TaskList.CHECKED_SOCIAL_MEDIA,
    type: TaskType.WEEKLY,
    title: 'Проверить соцсети',
    description:
      'Подпишитесь на социальные сети проекта, чтобы всегда быть в курсе последних событий',
    goal: 2,
    rewardSp: 25,
  },
  {
    key: TaskList.SUBSCRIBED_SOUL_FORUM,
    type: TaskType.WEEKLY,
    title: 'Подписаться на SOUL forum',
    description:
      'На форуме можно познакомиться с локальными сообществами из разных стран, получить ответы от местных жителей, а также рассказать о себе',
    goal: 1,
    rewardSp: 0,
  },
  {
    key: TaskList.SUBSCRIBED_INSTAGRAM,
    type: TaskType.WEEKLY,
    title: 'Подписаться на Instagram проекта',
    description:
      'В Instagram мы публикуем важные новости, репостим сториз со встреч, рассказываем о локальных сообществах из разных стран',
    goal: 1,
    rewardSp: 0,
  },
  {
    key: TaskList.SHARED_ABOUT_SOUL,
    type: TaskType.WEEKLY,
    title: 'Рассказать о SOUL',
    description: 'Расскажите своим друзьям о приложении SOUL',
    goal: 2,
    rewardSp: 100,
  },
  {
    key: TaskList.SHARED_WITH_FRIEND,
    type: TaskType.WEEKLY,
    title: 'Отправить сообщение другу',
    description:
      'Пригласите друга в приложение SOUL, но советуем звать только тех, кому это может быть действительно интересно и полезно',
    goal: 1,
    rewardSp: 0,
  },
  {
    key: TaskList.ADDED_REFLINK_IN_TG_PROFILE,
    type: TaskType.WEEKLY,
    title: 'Добавить реферальную ссылку в свой Telegram профиль',
    description:
      'Скопируйте реферальную ссылку и добавьте ее в описание своего профиля в Telegram - это поможет увеличить количество друзей',
    goal: 1,
    rewardSp: 0,
  },
  {
    key: TaskList.PREMIUM_SUPPORT,
    type: TaskType.WEEKLY,
    title: 'Premium поддержка',
    description:
      'Заработайте дополнительные SOUL points, если у вас есть подписка Telegram Premium',
    goal: 2,
    rewardSp: 300,
  },
  {
    key: TaskList.VOTED_SOUL_FORUM,
    type: TaskType.WEEKLY,
    title: 'Проголосовать за SOUL forum',
    description:
      'Это поможет нам расширить функционал форума и открыть новые возможности оформления от Telegram',
    goal: 1,
    rewardSp: 0,
  },
  {
    key: TaskList.SHARED_STORY_IN_TG,
    type: TaskType.WEEKLY,
    title: 'Поделиться историей в Telegram',
    description:
      'Расскажите в истории о ближайшей встрече, на которую вы пойдете, и позовите на нее своих друзей',
    goal: 1,
    rewardSp: 0,
  },
  {
    key: TaskList.PROFILE_COMPLETED,
    type: TaskType.SECTION_TRAINING,
    title: 'Заполните профиль',
    description: 'Заполните свой профиль, чтобы получить награду!',
    goal: 1,
    rewardSp: 50,
  },
  {
    key: TaskList.VIEWED_HOW_IT_WORKS,
    type: TaskType.SECTION_TRAINING,
    title: 'Посмотрите раздел «Как это работает»',
    description:
      'Посмотрите раздел «Как это работает», чтобы получить награду!',
    goal: 1,
    rewardSp: 50,
  },
  {
    key: TaskList.CREATED_FIRST_MEETING,
    type: TaskType.SECTION_MEETINGS,
    title: 'Создайте свою первую встречу',
    description: 'Проводите встречи, чтобы получить награду!',
    goal: 1,
    rewardSp: 100,
  },
  {
    key: TaskList.HOLDED_MEETINGS,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите встречу',
    description: 'Проводите встречи, чтобы получить награды!',
    goal: 0, // без лимита - гланый ключ для проверки
    rewardSp: 0,
  },
  {
    key: TaskList.HOLDED_1_MEETINGS,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите 1 встречу',
    description: 'Проводите встречи, чтобы получить награды!',
    goal: 1,
    rewardSp: 100,
  },
  {
    key: TaskList.HOLDED_5_MEETINGS,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите 5 встреч',
    description: 'Проводите встречи, чтобы получить награды!',
    goal: 5,
    rewardSp: 500,
  },
  {
    key: TaskList.HOLDED_10_MEETINGS,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите 10 встреч',
    description: 'Проводите встречи, чтобы получить награды!',
    goal: 10,
    rewardSp: 1000,
  },
  {
    key: TaskList.HOLDED_20_MEETINGS,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите 20 встреч',
    description: 'Проводите встречи, чтобы получить награды!',
    goal: 20,
    rewardSp: 2000,
  },
  {
    key: TaskList.HOLDED_50_MEETINGS,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите 50 встреч',
    description: 'Проводите встречи, чтобы получить награды!',
    goal: 50,
    rewardSp: 5000,
  },
  {
    key: TaskList.MAX_GUESTS_IN_MEETING,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите встречу на N гостей',
    description: 'Принимайте больше гостей, чтобы получить награды!',
    goal: 0, // без лимита - гланый ключ для проверки
    rewardSp: 0,
  },
  {
    key: TaskList.MAX_GUESTS_5_IN_MEETING,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите встречу на 5 гостей',
    description: 'Принимайте больше гостей, чтобы получить награды!',
    goal: 5,
    rewardSp: 1000,
  },
  {
    key: TaskList.MAX_GUESTS_10_IN_MEETING,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите встречу на 10 гостей',
    description: 'Принимайте больше гостей, чтобы получить награды!',
    goal: 10,
    rewardSp: 2000,
  },
  {
    key: TaskList.MAX_GUESTS_20_IN_MEETING,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите встречу на 20 гостей',
    description: 'Принимайте больше гостей, чтобы получить награды!',
    goal: 20,
    rewardSp: 4000,
  },
  {
    key: TaskList.MAX_GUESTS_50_IN_MEETING,
    type: TaskType.SECTION_MEETINGS,
    title: 'Проведите встречу на 50 гостей',
    description: 'Принимайте больше гостей, чтобы получить награды!',
    goal: 50,
    rewardSp: 10000,
  },
  {
    key: TaskList.INVITED_FRIENDS,
    type: TaskType.SECTION_FRIENDS,
    title: 'Пригласите друга',
    description: 'Приглашайте своих друзей, чтобы получить награды!',
    goal: 0, // без лимита - гланый ключ для проверки
    rewardSp: 0,
  },
  {
    key: TaskList.INVITED_1_FRIENDS,
    type: TaskType.SECTION_FRIENDS,
    title: 'Пригласите 1 друга',
    description: 'Приглашайте своих друзей, чтобы получить награды!',
    goal: 1,
    rewardSp: 200,
  },
  {
    key: TaskList.INVITED_5_FRIENDS,
    type: TaskType.SECTION_FRIENDS,
    title: 'Пригласите 5 друзей',
    description: 'Приглашайте своих друзей, чтобы получить награды!',
    goal: 1,
    rewardSp: 200,
  },
  {
    key: TaskList.INVITED_10_FRIENDS,
    type: TaskType.SECTION_FRIENDS,
    title: 'Пригласите 10 друзей',
    description: 'Приглашайте своих друзей, чтобы получить награды!',
    goal: 1,
    rewardSp: 200,
  },
  {
    key: TaskList.INVITED_20_FRIENDS,
    type: TaskType.SECTION_FRIENDS,
    title: 'Пригласите 20 друзей',
    description: 'Приглашайте своих друзей, чтобы получить награды!',
    goal: 1,
    rewardSp: 200,
  },
  {
    key: TaskList.INVITED_50_FRIENDS,
    type: TaskType.SECTION_FRIENDS,
    title: 'Пригласите 50 друзей',
    description: 'Приглашайте своих друзей, чтобы получить награды!',
    goal: 1,
    rewardSp: 200,
  },
  {
    key: TaskList.INVITED_100_FRIENDS,
    type: TaskType.SECTION_FRIENDS,
    title: 'Пригласите 100 друзей',
    description: 'Приглашайте своих друзей, чтобы получить награды!',
    goal: 1,
    rewardSp: 200,
  },
  {
    key: TaskList.COLLECTED_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 0, // без лимита - гланый ключ для проверки
    rewardSp: 0,
  },
  {
    key: TaskList.COLLECTED_10_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 10 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 10,
    rewardSp: 50,
  },
  {
    key: TaskList.COLLECTED_50_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 50 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 50,
    rewardSp: 200,
  },
  {
    key: TaskList.COLLECTED_100_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 100 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 100,
    rewardSp: 500,
  },
  {
    key: TaskList.COLLECTED_250_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 250 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 250,
    rewardSp: 1000,
  },
  {
    key: TaskList.COLLECTED_500_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 500 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 500,
    rewardSp: 2000,
  },
  {
    key: TaskList.COLLECTED_1000_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 1000 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 1000,
    rewardSp: 5000,
  },
  {
    key: TaskList.COLLECTED_2500_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 2500 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 2500,
    rewardSp: 10000,
  },
  {
    key: TaskList.COLLECTED_5000_SP,
    type: TaskType.SECTION_FARMING,
    title: 'Соберите 5000 SP',
    description: 'Собирайте SP, чтобы получить награды!',
    goal: 5000,
    rewardSp: 20000,
  },
];
