-- CreateEnum
CREATE TYPE "ExperienceType" AS ENUM ('MEETING_VISIT', 'MEETING_RATE', 'OWN_MEETING_PER_GUEST', 'OWN_MEETING_PER_RATING_1', 'OWN_MEETING_PER_RATING_2', 'OWN_MEETING_PER_RATING_3', 'OWN_MEETING_PER_RATING_4', 'OWN_MEETING_PER_RATING_5', 'FRIENDS_PER_INVITE', 'FARMING_PER_TIMER');

-- CreateTable
CREATE TABLE "Experience" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "value" INTEGER NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "ExperienceType" NOT NULL,

    CONSTRAINT "Experience_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Experience" ADD CONSTRAINT "Experience_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
